ORG 0000H
SJMP MAIN
ORG 0050H
MAIN:SETB P0.0;CONFIGURE P0.0 AS INPUT(SWITCH-1)
SETB P0.1;CONFIGURE P0.1 AS INPUT(SWITCH-2)
SETB P0.2;CONFIGURE P0.2 AS OUTPUT(LED)
LOOP:MOV C,P0.0;CONTENT P0.0 IS MOVED TO CARRY BIT
CPL C;COMPLEMENT THE CARRY BIT
MOV 00H,C;CONTENT CARRY BIT IS MOVED TO OOH LOCATION
MOV C,P0.1;CONTENT P0.1 IS MOVED TO C
CPL C;COMPLEMENT THE CARRY BIT
ORL C,00H;PERFORMING OR OPERATION BETWEEN 00H LOCATION AND CARRY BIT
CPL C;COMPLEMENT THE CARRY BIT
MOV P0.2,C;CONTENT CARRY BIT IS MOVED TO P0.2
SJMP LOOP;LOOP FUNCTION
END
